/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MonsterBookInterface extends ethers.utils.Interface {
  functions: {
    "getAction1(uint256)": FunctionFragment;
    "getAction2(uint256)": FunctionFragment;
    "getAlignment(uint256)": FunctionFragment;
    "getLanguage(uint256)": FunctionFragment;
    "getLocomotion(uint256)": FunctionFragment;
    "getName(uint256)": FunctionFragment;
    "getSize(uint256)": FunctionFragment;
    "getSpecialAbility(uint256)": FunctionFragment;
    "getWeakness(uint256)": FunctionFragment;
    "random(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAction1",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAction2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAlignment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLanguage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLocomotion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSpecialAbility",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWeakness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "random", values: [string]): string;

  decodeFunctionResult(functionFragment: "getAction1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAction2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAlignment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLanguage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLocomotion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSpecialAbility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWeakness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "random", data: BytesLike): Result;

  events: {};
}

export class MonsterBook extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MonsterBookInterface;

  functions: {
    getAction1(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getAction1(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getAction2(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getAction2(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getAlignment(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getAlignment(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getLanguage(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLanguage(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getLocomotion(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getLocomotion(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getName(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getName(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getSize(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getSize(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getSpecialAbility(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getSpecialAbility(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getWeakness(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getWeakness(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    random(
      input: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "random(string)"(
      input: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  getAction1(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAction1(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getAction2(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAction2(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getAlignment(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getAlignment(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getLanguage(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getLanguage(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getLocomotion(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getLocomotion(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getName(monsterId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getName(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getSize(monsterId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "getSize(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getSpecialAbility(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getSpecialAbility(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getWeakness(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getWeakness(uint256)"(
    monsterId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  random(input: string, overrides?: CallOverrides): Promise<BigNumber>;

  "random(string)"(
    input: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getAction1(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAction1(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getAction2(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAction2(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getAlignment(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getAlignment(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getLanguage(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getLanguage(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getLocomotion(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getLocomotion(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getName(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getName(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getSize(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSize(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getSpecialAbility(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSpecialAbility(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getWeakness(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getWeakness(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    random(input: string, overrides?: CallOverrides): Promise<BigNumber>;

    "random(string)"(
      input: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getAction1(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAction1(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAction2(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAction2(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAlignment(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAlignment(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLanguage(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLanguage(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLocomotion(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLocomotion(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getName(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getName(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSize(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSize(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSpecialAbility(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSpecialAbility(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWeakness(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getWeakness(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    random(input: string, overrides?: CallOverrides): Promise<BigNumber>;

    "random(string)"(
      input: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAction1(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAction1(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAction2(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAction2(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAlignment(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAlignment(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLanguage(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLanguage(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLocomotion(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLocomotion(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getName(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getName(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSize(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSize(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSpecialAbility(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSpecialAbility(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWeakness(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getWeakness(uint256)"(
      monsterId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    random(
      input: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "random(string)"(
      input: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
